apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: demo
  data:
    - secretKey: password
      remoteRef:
        key: demo
        property: password
