global:
  env:
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-bootstrap
          key: secret-key
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-bootstrap
          key: db-password
    - name: AUTHENTIK_BOOTSTRAP_PASSWORD_HASH
      valueFrom:
        secretKeyRef:
          name: authentik-bootstrap
          key: user-password-hash
    - name: HOMELAB_USER_PASSWORD_HASH
      valueFrom:
        secretKeyRef:
          name: authentik-bootstrap
          key: user-password-hash
    - name: ARGOCD_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: authentik-oidc-clients
          key: argocd
    - name: OPENBAO_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: authentik-oidc-clients
          key: openbao

blueprints:
  configMaps:
    - authentik-blueprints

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - auth.localtest.me

postgresql:
  enabled: true
  auth:
    existingSecret: authentik-bootstrap
    secretKeys:
      adminPasswordKey: db-password
      userPasswordKey: db-password
  primary:
    persistence:
      size: 1Gi
