global:
  domain: argocd.localtest.me

configs:
  cm:
    url: http://argocd.localtest.me:8080
    oidc.config: |
      name: Authentik
      issuer: http://auth.localtest.me:8080/application/o/argocd/
      clientID: argocd
      clientSecret: $argocd-oidc:clientSecret
      requestedScopes: ["openid", "profile", "email"]
