injector:
  enabled: false

server:
  dataStorage:
    size: 1Gi

  extraSecretEnvironmentVars:
    - envName: UNSEAL_KEY
      secretName: openbao-bootstrap
      secretKey: unseal-key
    - envName: USER_PASSWORD
      secretName: openbao-bootstrap
      secretKey: user-password
    - envName: OIDC_CLIENT_SECRET
      secretName: openbao-oidc
      secretKey: client-secret

  ingress:
    enabled: true
    ingressClassName: traefik
