ports:
  web:
    exposedPort: 80
    asDefault: true
    forwardedHeaders:
      trustedIPs:
        - 10.42.0.0/16
  websecure:
    asDefault: true

service:
  spec:
    type: LoadBalancer

providers:
  kubernetesIngress:
    publishedService:
      enabled: true

ingressRoute:
  dashboard:
    matchRule: Host(`traefik.sebhome.homes`)
