nodeSelector:
  ingress-ready: "true"

updateStrategy:
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 0

ports:
  web:
    hostPort: 80
  websecure:
    hostPort: 443

service:
  spec:
    type: ClusterIp

providers:
  kubernetesIngress:
    publishedService:
      enabled: false
    ingressEndpoint:
      ip: 127.0.0.1

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.localhost.me`)
    entryPoints: ["web"]
