apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-config
  namespace: argocd

spec:
  project: default
  sources:
    - repoURL: https://github.com/sebesjoberg/home-lab
      targetRevision: main
      path: infra/external-secrets/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
