global:
  domain: argocd.sebhome.homes

configs:
  cm:
    url: https://argocd.sebhome.homes
    oidc.config: |
      name: Authentik
      issuer: https://auth.sebhome.homes/application/o/argocd/
      clientID: argocd
      clientSecret: $argocd-oidc:clientSecret
      requestedScopes: ["openid", "profile", "email"]
