global:
  domain: argocd.lab.home

configs:
  cm:
    url: http://argocd.lab.home
    oidc.config: |
      name: Authentik
      issuer: http://auth.lab.home/application/o/argocd/
      clientID: argocd
      clientSecret: $argocd-oidc:clientSecret
      requestedScopes: ["openid", "profile", "email"]
