global:
  domain: argocd.localtest.me

configs:
  params:
    server.insecure: true
  cm:
    timeout.reconciliation: 180s
    resource.customizations.health.argoproj.io_Application: |
      hs = {}
      hs.status = "Progressing"
      hs.message = ""
      if obj.status ~= nil and obj.status.health ~= nil then
        hs.status = obj.status.health.status
        if obj.status.health.message ~= nil then
          hs.message = obj.status.health.message
        end
      end
      return hs

server:
  ingress:
    enabled: true
    ingressClassName: traefik
dex:
  enabled: false
notifications:
  enabled: false
