global:
  domain: argocd.localtest.me

configs:
  params:
    server.insecure: true
  cm:
    url: http://argocd.localtest.me:8080
    timeout.reconciliation: 180s
    oidc.config: |
      name: Authentik
      issuer: http://auth.localtest.me:8080/application/o/argocd/
      clientID: argocd
      clientSecret: $argocd-oidc:clientSecret
      requestedScopes: ["openid", "profile", "email"]
    resource.customizations.health.argoproj.io_Application: |
      hs = {}
      hs.status = "Progressing"
      hs.message = ""
      if obj.status ~= nil and obj.status.health ~= nil then
        hs.status = obj.status.health.status
        if obj.status.health.message ~= nil then
          hs.message = obj.status.health.message
        end
      end
      return hs
  rbac:
    policy.default: ""
    policy.csv: |
      g, admins, role:admin

server:
  ingress:
    enabled: true
    ingressClassName: traefik
dex:
  enabled: false
notifications:
  enabled: false
